---
- name: restart jupyter
  become: yes
  become_method: sudo
  service:
    name: "{{ jupyter_servicename }}"
    state: restarted

- name: reload-daemon
  service:
    name: "{{ systemreload_servicename }}"
    daemon_reload: yes
